#!/bin/env bash

#
# Seed mapper. 
# Read info from file of the form:
# seeds: <seed list>
# 
# a-to-b-map:
# dst src len
# ...
# 
# c-to-d-map:
# dst src len
# ...
#
# etc.
#
# If no mapping provided for a number, number not mapped
#
# Print out the lowest location number for the input seeds
# (the location number is the last mapping)
#
readmap() 
{
  index=$1
  mapinput=$*
  header=$rawtext[${index}]
  index=$((index+1))
  line=${rawtext[${index}]}
  while ! [ -z "${line}" ]; do
    index=$((index+1))
    line=${rawtext[${index}]}
  done
  echo "1 2 3 4"
  return $index
} 

mapfile=$1
while IFS= read -r line; do
  rawtext[${i}]="$line"
  i=$((i+1))
done < ${mapfile}

seeds=${rawtext[0]}
blankline=${rawtext[1]}

map=$(echo $seeds | cut -d' ' -f 2-)
index=2
while [ ${index} -lt ${#rawtext[@]} ] ; do
  echo "${map}"
  map=$(readmap ${index})
  index=$?
done
