#!/bin/sh
set -e
myhlq=$(hlq)
mydir="$(cd "$(dirname "$0")" > /dev/null 2>&1 && pwd -P)"

drm -f "${myhlq}.user.load"
dtouch -ru "${myhlq}.user.load"

export STEPLIB=IGY.V6R4M0.SIGYCOMP:IGY.V6R4M0.SIGYLIB
cob2 -orace race.cbl

dcp "${mydir}/race" "${myhlq}.user.load(race)"
rm -f "${mydir}/race"
